### ISSUE TITLE
Cached image exception

### ISSUE THREAD

**Issue by fra967** [dadi/cdn#392]
We had an occurrence of an existing image being cached in a way that all subsequent requests were returning the exception below and crashing the cluster worker.
Once the cache for this image was flushed, it worked ok.
We cannot reproduce what created this problem in the cache, but we are keeping an eye on logs and will provide more info in case it happens again. Possibly the error log can provide some clues?
Cache is file-based, cache404 is set to false

```
ERROR] TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/dadi/cdn/node_modules/etag/index.js:83:11)
    at sendBuffer (/dadi/cdn/node_modules/@dadi/cdn/dadi/lib/controller/index.js:65:28)
    at ConcatStream.<anonymous> (/dadi/cdn/node_modules/concat-stream/index.js:37:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/dadi/cdn/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/dadi/cdn/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/dadi/cdn/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at PassThroughExt.onend (/dadi/cdn/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at PassThroughExt.emit (events.js:208:7)
    at /dadi/cdn/node_modules/pass-stream/node_modules/readable-stream/lib/_stream_readable.js:875:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) 'Uncaught Exception thrown'

```

**Comment by eduardoboucas** [comment]
Can you let me know if this is still an issue in 3.1.0?

**Comment by fra967** [comment]
No, but I could not even reproduce it with the previous version, let's close it for now, I will re-open in case it re-occurs
