### ISSUE TITLE
Failed image type detection

### ISSUE THREAD

**Issue by fra967** [dadi/cdn#393]
Image detection is failing for some JPGs with the following error

JPG provided separately

```
[2018-06-29T10:16:33.001Z] ERROR: dadi-cdn/5160 on ip-172-31-1-4: Reached the limit before detecting image type.
    Error: Reached the limit before detecting image type.
        at PassThrough.detectImageSize (/dadi/cdn/node_modules/image-size-stream/index.js:46:30)
        at emitOne (events.js:116:13)
        at PassThrough.emit (events.js:211:7)
        at readableAddChunk (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_readable.js:195:16)
        at PassThrough.Readable.push (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_readable.js:162:10)
        at PassThrough.Transform.push (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_transform.js:145:32)
        at afterTransform (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_transform.js:101:12)
        at TransformState.afterTransform (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_transform.js:79:12)
        at PassThrough._transform (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_passthrough.js:45:3)
        at PassThrough.Transform._read (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_transform.js:184:10)
        at PassThrough.Transform._write (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_transform.js:172:12)
        at doWrite (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_writable.js:279:12)
        at writeOrBuffer (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_writable.js:266:5)
        at PassThrough.Writable.write (/dadi/cdn/node_modules/image-size-stream/node_modules/readable-stream/lib/_stream_writable.js:211:11)
        at PassThrough.ondata (_stream_readable.js:639:20)
        at emitOne (events.js:116:13)
        at PassThrough.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at PassThrough.Readable.push (_stream_readable.js:208:10)
        at PassThrough.Transform.push (_stream_transform.js:147:32)
        at PassThrough.afterTransform (_stream_transform.js:88:10)
        at PassThrough._transform (_stream_passthrough.js:42:3)
        at PassThrough.Transform._read (_stream_transform.js:186:10)
        at PassThrough.Transform._write (_stream_transform.js:174:12)
        at doWrite (_stream_writable.js:397:12)
        at writeOrBuffer (_stream_writable.js:383:5)
        at PassThrough.Writable.write (_stream_writable.js:290:11)
        at MultiStream.ondata (_stream_readable.js:639:20)
        at emitOne (events.js:121:20)
        at MultiStream.emit (events.js:211:7)
        at MultiStream.Readable.read (_stream_readable.js:475:10)
        at flow (_stream_readable.js:846:34)
        at resume_ (_stream_readable.js:828:3)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by fra967** [comment]
thank you, all good
