### ISSUE TITLE
version nodejs 12.1

### ISSUE THREAD

**Issue by jaffarc** [dadi/cdn#517]
i need update version nodejs to 12.1 . 

it error start cdn..

`} Uncaught Exception thrown
[2020-02-20 22:18:45.888] [ERROR]  Trace
    at process.<anonymous> (/var/www/cdn/viamaker/node_modules/@dadi/cdn/dadi/lib/index.js:31:13)
    at process.emit (events.js:201:15)
    at process.EventEmitter.emit (domain.js:471:20)
    at processEmit [as emit] (/var/www/cdn/viamaker/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (internal/process/execution.js:142:25)
`

delete node_modules  and npm i 

`prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/var/www/cdn/viamaker/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:27:0:
../src/common.h:78:20: error: ‘Handle’ is not a member of ‘v8’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                    ^~~~~~
../src/common.h:78:37: error: expected primary-expression before ‘>’ token
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                     ^
../src/common.h:78:39: error: ‘obj’ was not declared in this scope
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                       ^~~
../src/common.h:78:56: error: expected primary-expression before ‘attr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                        ^~~~
../src/common.h:78:60: error: expression list treated as compound expression in initializer [-fpermissive]
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                            ^
../src/common.h:79:29: error: ‘Handle’ is not a member of ‘v8’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                             ^~~~~~
../src/common.h:79:46: error: expected primary-expression before ‘>’ token
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                              ^
`

**Comment by nika-begiashvili** [comment]
same here

**Comment by jaffarc** [comment]
@nika-begiashvili  i resolved with :
`
npm install --save @dadi/cdn  --arch=x64 --platform=linux sharp
`
